
server:
  port: 8088

spring:
  application:
    name: resume-management

  devtools:
    restart:
      enabled: true

    livereload:
      enabled: true

  thymeleaf:
    cache: false

  security:
    user:
      name: test@test.com
      password: 1111


  #################
  #Mysql Setting
  #################

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resume_management_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678

  #################
  #JPA Setting
  #################

  jpa:
    open-in-view: true
    hibernate:
      ddl_auto: update  # create, update, none, create-drop, validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # ????? ???? ??? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 ?? ??

#################
#Log Setting
#################

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace